const PRICE_LIST = [
{id:1,ownership:"shared",service:"Netflix",package:"Premium",price:65,duration:"Monthly",description:"Netflix Premium shared slot",status:"active"},
{id:2,ownership:"private",service:"Netflix",package:"Mobile",price:160,duration:"Monthly",description:"Private Netflix Mobile",status:"active"},
{id:3,ownership:"private",service:"Netflix",package:"Basic",price:250,duration:"Monthly",description:"Private Netflix Basic",status:"active"},
{id:4,ownership:"private",service:"Netflix",package:"Standard",price:350,duration:"Monthly",description:"Private Netflix Standard",status:"active"},
{id:5,ownership:"private",service:"Netflix",package:"Premium",price:399,duration:"Monthly",description:"Private Netflix Premium",status:"active"},
{id:6,ownership:"shared",service:"Prime Video",package:"Shared",price:80,duration:"Monthly",description:"Prime Video shared access",status:"active"},
{id:7,ownership:"private",service:"Amazon Prime Video",package:"Private",price:250,duration:"Monthly",description:"Private Amazon Prime Video",status:"active"},
{id:8,ownership:"shared",service:"Spotify",package:"Individual Slot",price:60,duration:"Monthly",description:"Spotify shared slot",status:"active"},
{id:9,ownership:"private",service:"Spotify",package:"Individual",price:150,duration:"Monthly",description:"Private Spotify Individual",status:"active"},
{id:10,ownership:"private",service:"Spotify",package:"Family",price:250,duration:"Monthly",description:"Private Spotify Family",status:"active"},
{id:11,ownership:"shared",service:"Apple Music",package:"Slot",price:80,duration:"Monthly",description:"Apple Music shared slot",status:"active"},
{id:12,ownership:"private",service:"Apple Music",package:"Individual",price:180,duration:"Monthly",description:"Private Apple Music",status:"active"},
{id:13,ownership:"private",service:"Apple Music",package:"Family",price:300,duration:"Monthly",description:"Apple Music Family",status:"active"},
{id:14,ownership:"shared",service:"iCloud",package:"50GB",price:50,duration:"Monthly",description:"iCloud 50GB",status:"active"},
{id:15,ownership:"shared",service:"iCloud",package:"200GB",price:80,duration:"Monthly",description:"iCloud 200GB",status:"active"},
{id:16,ownership:"private",service:"iCloud",package:"50GB",price:80,duration:"Monthly",description:"Private iCloud 50GB",status:"active"},
{id:17,ownership:"private",service:"iCloud",package:"200GB",price:150,duration:"Monthly",description:"Private iCloud 200GB",status:"active"},
{id:18,ownership:"private",service:"iCloud",package:"2TB",price:300,duration:"Monthly",description:"Private iCloud 2TB",status:"active"},
{id:19,ownership:"shared",service:"Gemini AI",package:"Plus",price:50,duration:"Monthly",description:"Gemini AI Plus",status:"active"},
{id:20,ownership:"private",service:"Gemini AI",package:"Plus",price:100,duration:"Monthly",description:"Private Gemini AI Plus",status:"active"},
{id:21,ownership:"private",service:"Gemini AI",package:"Pro",price:150,duration:"Monthly",description:"Private Gemini AI Pro",status:"active"},
{id:22,ownership:"shared",service:"DSTV Stream",package:"2 Weeks",price:150,duration:"2 Weeks",description:"DSTV Stream",status:"active"},
{id:23,ownership:"private",service:"DSTV Stream",package:"Promo",price:250,duration:"Monthly",description:"DSTV Stream private promo",status:"active"}
];